from setuptools import setup

setup(
    name='st_webcam',
    version='0.0.1',    
    description='Effortless webcam integration for computer vision projects with Streamlit.',
    url='https://github.com/SaarthRajan/st_webcam',
    author='Saarth Rajan',
    author_email='saarth.rajan@uwaterloo.ca',
    license='MIT',
    packages=['st_webcam'],
    install_requires=[
        "altair==5.4.1",
        "annotated-types==0.7.0",
        "anyio==4.6.2.post1",
        "attrs==24.2.0",
        "blinker==1.8.2",
        "cachetools==5.5.0",
        "certifi==2024.8.30",
        "charset-normalizer==3.4.0",
        "click==8.1.7",
        "distro==1.9.0",
        "gitdb==4.0.11",
        "GitPython==3.1.43",
        "h11==0.14.0",
        "httpcore==1.0.7",
        "httpx==0.27.2",
        "idna==3.10",
        "Jinja2==3.1.4",
        "jiter==0.7.1",
        "jsonschema==4.23.0",
        "jsonschema-specifications==2024.10.1",
        "markdown-it-py==3.0.0",
        "MarkupSafe==3.0.2",
        "mdurl==0.1.2",
        "narwhals==1.13.1",
        "opencv-python==4.10.0.84",
        "packaging==24.1",
        "pandas==2.2.3",
        "pillow==10.4.0",
        "pyarrow==18.0.0",
        "pydantic==2.9.2",
        "pydantic_core==2.23.4",
        "pydeck==0.9.1",
        "Pygments==2.18.0",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.2",
        "referencing==0.35.1",
        "requests==2.32.3",
        "rich==13.9.4",
        "rpds-py==0.20.1",
        "setuptools",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.1",
        "streamlit==1.39.0",
        "tenacity==9.0.0",
        "toml==0.10.2",
        "tornado==6.4.1",
        "tqdm==4.67.0",
        "typing_extensions==4.12.2",
        "tzdata==2024.2"
    ],

    classifiers=[
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Development Status :: 4 - Beta",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Computer Vision",
        "Topic :: Software Development :: Libraries :: Streamlit",
        "Natural Language :: English",
    ]
)